/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by Voice CodeGen Version: R1_v1.3.0
* generated on: Tue Jun 21 15:32:43 IST 2016
*/
/**
 * description: Tuner generic and project independent interface for additional services. This
 *   interface provides functions to request data services and to configure them.
 *   Other services like announcements can also be configured.
 * author: EGMG_Tuner
 */
#ifndef V2_IVIRADIO_ADDITIONALSERVICE_ADDITIONAL_SERVICE_HPP_
#define V2_IVIRADIO_ADDITIONALSERVICE_ADDITIONAL_SERVICE_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Types.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v2 {
namespace IVIRadio {
namespace AdditionalService {

class AdditionalService {
public:
    virtual ~AdditionalService() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* AdditionalService::getInterface() {
    return ("IVIRadio.AdditionalService.AdditionalService");
}

CommonAPI::Version AdditionalService::getInterfaceVersion() {
    return CommonAPI::Version(2, 1);
}


} // namespace AdditionalService
} // namespace IVIRadio
} // namespace v2

namespace CommonAPI {
}


// Compatibility
namespace v2_1 = v2;

#endif // V2_IVIRADIO_ADDITIONALSERVICE_ADDITIONAL_SERVICE_HPP_
