/**********************************************************************
 *  Project       Harman Car Multimedia System
 *  (c) copyright 2014
 *  Company       Harman/Becker Automotive Systems GmbH
 *                All rights reserved
 **********************************************************************/

/*
 * Generated by DSI Generator version 2.0
 * Date: 21.11.2014
 */



/*
 * Remove the const from the attributes for this module.
 */
#define DSICONST

#include "DMMAmFmTunerDiranaControlClient.h"


/*** synchronous methods *******************************************************************/

/*** synchronous attribute notifications ***************************************************/


/*******************************************************************************************/
