#ifndef DMMAMFMTUNERDIRANACONTROL_H
#define DMMAMFMTUNERDIRANACONTROL_H
/**********************************************************************
 *  Project       Harman Car Multimedia System
 *  (c) copyright 2014
 *  Company       Harman/Becker Automotive Systems GmbH
 *                All rights reserved
 **********************************************************************/

/*
 * Generated by DSI Generator version 2.0
 * Date: 21.11.2014
 */


#include "api/sys/dsi/pf/base/src/DSI.h"

DSI_EXTERN_C_BEGIN


// Version information

static const int DMMAmFmTunerDiranaControl_MAJOR_VERSION = 1 ;
static const int DMMAmFmTunerDiranaControl_MINOR_VERSION = 1 ;


/** ***************************************************************************
 *  DMMAmFmTunerDiranaControl
 *
 *  Interface for control of Dirana audio routing, for experts only.
 */
typedef enum
{
   /**
    * Changes Dirana audio routing: Connect input with output.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_requestSetAudioRouting = DSI_REQUEST_ID_FIRST + 0, // 0x00000000

   /**
    * Get current audio input connected with given output.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_requestGetAudioRouting = DSI_REQUEST_ID_FIRST + 1, // 0x00000001

   /**
    * Writes a single memory location with a 24-bit value in the dirana and returns the result of the operation in the corresponding response.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_requestWriteXMem = DSI_REQUEST_ID_FIRST + 2, // 0x00000002

   /**
    * Reads a single memory address from the dirana and returns the value in the corresponding response
    */
   DMMAmFmTunerDiranaControl_UPD_ID_requestReadXMem = DSI_REQUEST_ID_FIRST + 3, // 0x00000003

   /**
    * Writes a single memory location with a 16-bit value in the dirana and returns the result of the operation in the corresponding response.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_requestWriteYMem = DSI_REQUEST_ID_FIRST + 4, // 0x00000004

   /**
    * Reads a single memory address from the dirana and returns the value in the corresponding response
    */
   DMMAmFmTunerDiranaControl_UPD_ID_requestReadYMem = DSI_REQUEST_ID_FIRST + 5, // 0x00000005

   /**
    * Returns success state of request, notifcation has to be set manually.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_responseSetAudioRouting = DSI_RESPONSE_ID_FIRST + 0, // 0x80000000

   /**
    * Returns requested audio input
    */
   DMMAmFmTunerDiranaControl_UPD_ID_responseGetAudioRouting = DSI_RESPONSE_ID_FIRST + 1, // 0x80000001

   /**
    * The response.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_responseReadXMem = DSI_RESPONSE_ID_FIRST + 2, // 0x80000002

   /**
    * The response.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_responseWriteXMem = DSI_RESPONSE_ID_FIRST + 3, // 0x80000003

   /**
    * The response.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_responseReadYMem = DSI_RESPONSE_ID_FIRST + 4, // 0x80000004

   /**
    * The response.
    */
   DMMAmFmTunerDiranaControl_UPD_ID_responseWriteYMem = DSI_RESPONSE_ID_FIRST + 5, // 0x80000005

   /**
    * Implementation version
    */
   DMMAmFmTunerDiranaControl_UPD_ID_implVersion = DSI_ATTRIBUTE_ID_LAST - 1,

   /**
    * Nothing
    */
   DMMAmFmTunerDiranaControl_UPD_ID_NOP = DSI_ATTRIBUTE_ID_LAST

} DMMAmFmTunerDiranaControl_UpdateIdEnum ;




/** ***************************************************************************
 * Audio inputs
 */
typedef enum
{
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_IIS1,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_IIS2,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_IIS3,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_IIS4,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_SPDIF1,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_SPDIF2,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_TUNER1,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_TUNER2,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_PHONE_DIGITAL,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_NAV_DIGITAL,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_AIN0,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_AIN1,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_AIN2,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_AIN3,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_AIN4,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_HOST_IIS1,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_HOST_IIS2,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_HOST_IIS3,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_HOST_IIS4,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_IN_HOST_IIS5,

} DMMAmFmTunerDiranaControl_AudioInputs ;


/** ***************************************************************************
 * Audio outputs
 */
typedef enum
{
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OUT_ANALOG_FRONT,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OUT_ANALOG_REAR,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OUT_ANALOG_SUB,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OUT_IIS1,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OUT_IIS2,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OUT_IIS3,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OUT_IIS4,

} DMMAmFmTunerDiranaControl_AudioOutputs ;


/** ***************************************************************************
 * Possible request results
 */
typedef enum
{
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_OK,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_FAILED,
   /*
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_NOT_IMPLEMENTED,

} DMMAmFmTunerDiranaControl_Result ;



/** ***************************************************************************
 * Constants
 */



/** ***************************************************************************
 * Argument List Structure for requestDMMAmFmTunerDiranaControl_SetAudioRouting
 */
typedef struct _DMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList
{
   /**
    * Audio input
    */
   DMMAmFmTunerDiranaControl_AudioInputs input ;

   /**
    * Audio output
    */
   DMMAmFmTunerDiranaControl_AudioOutputs output ;

} DMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList ;

#define DMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_RequestSetAudioRoutingArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for requestDMMAmFmTunerDiranaControl_GetAudioRouting
 */
typedef struct _DMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList
{
   /**
    * Audio output
    */
   DMMAmFmTunerDiranaControl_AudioOutputs output ;

} DMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList ;

#define DMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_RequestGetAudioRoutingArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for requestDMMAmFmTunerDiranaControl_WriteXMem
 */
typedef struct _DMMAmFmTunerDiranaControl_RequestWriteXMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   unsigned int memAddress ;

   /**
    * DESCRIPTION MISSING
    */
   unsigned int memValueX ;

} DMMAmFmTunerDiranaControl_RequestWriteXMemArgList ;

#define DMMAmFmTunerDiranaControl_RequestWriteXMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_RequestWriteXMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_RequestWriteXMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_RequestWriteXMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_RequestWriteXMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_RequestWriteXMemArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for requestDMMAmFmTunerDiranaControl_ReadXMem
 */
typedef struct _DMMAmFmTunerDiranaControl_RequestReadXMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   unsigned int memAddress ;

} DMMAmFmTunerDiranaControl_RequestReadXMemArgList ;

#define DMMAmFmTunerDiranaControl_RequestReadXMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_RequestReadXMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_RequestReadXMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_RequestReadXMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_RequestReadXMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_RequestReadXMemArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for requestDMMAmFmTunerDiranaControl_WriteYMem
 */
typedef struct _DMMAmFmTunerDiranaControl_RequestWriteYMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   unsigned int memAddress ;

   /**
    * DESCRIPTION MISSING
    */
   unsigned short memValueY ;

} DMMAmFmTunerDiranaControl_RequestWriteYMemArgList ;

#define DMMAmFmTunerDiranaControl_RequestWriteYMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_RequestWriteYMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_RequestWriteYMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_RequestWriteYMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_RequestWriteYMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_RequestWriteYMemArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for requestDMMAmFmTunerDiranaControl_ReadYMem
 */
typedef struct _DMMAmFmTunerDiranaControl_RequestReadYMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   unsigned int memAddress ;

} DMMAmFmTunerDiranaControl_RequestReadYMemArgList ;

#define DMMAmFmTunerDiranaControl_RequestReadYMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_RequestReadYMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_RequestReadYMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_RequestReadYMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_RequestReadYMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_RequestReadYMemArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for responseDMMAmFmTunerDiranaControl_SetAudioRouting
 */
typedef struct _DMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList
{
   /**
    * Result of last request
    */
   DMMAmFmTunerDiranaControl_Result result ;

} DMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList ;

#define DMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_ResponseSetAudioRoutingArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for responseDMMAmFmTunerDiranaControl_GetAudioRouting
 */
typedef struct _DMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList
{
   /**
    * Audio input
    */
   DMMAmFmTunerDiranaControl_AudioInputs input ;

} DMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList ;

#define DMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_ResponseGetAudioRoutingArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for responseDMMAmFmTunerDiranaControl_ReadXMem
 */
typedef struct _DMMAmFmTunerDiranaControl_ResponseReadXMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_Result result ;

   /**
    * DESCRIPTION MISSING
    */
   unsigned int memValueX ;

} DMMAmFmTunerDiranaControl_ResponseReadXMemArgList ;

#define DMMAmFmTunerDiranaControl_ResponseReadXMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_ResponseReadXMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_ResponseReadXMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_ResponseReadXMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_ResponseReadXMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_ResponseReadXMemArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for responseDMMAmFmTunerDiranaControl_WriteXMem
 */
typedef struct _DMMAmFmTunerDiranaControl_ResponseWriteXMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_Result result ;

} DMMAmFmTunerDiranaControl_ResponseWriteXMemArgList ;

#define DMMAmFmTunerDiranaControl_ResponseWriteXMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_ResponseWriteXMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_ResponseWriteXMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_ResponseWriteXMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_ResponseWriteXMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_ResponseWriteXMemArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for responseDMMAmFmTunerDiranaControl_ReadYMem
 */
typedef struct _DMMAmFmTunerDiranaControl_ResponseReadYMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_Result result ;

   /**
    * DESCRIPTION MISSING
    */
   unsigned short memValueY ;

} DMMAmFmTunerDiranaControl_ResponseReadYMemArgList ;

#define DMMAmFmTunerDiranaControl_ResponseReadYMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_ResponseReadYMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_ResponseReadYMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_ResponseReadYMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_ResponseReadYMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_ResponseReadYMemArgList* arglist );



/** ***************************************************************************
 * Argument List Structure for responseDMMAmFmTunerDiranaControl_WriteYMem
 */
typedef struct _DMMAmFmTunerDiranaControl_ResponseWriteYMemArgList
{
   /**
    * DESCRIPTION MISSING
    */
   DMMAmFmTunerDiranaControl_Result result ;

} DMMAmFmTunerDiranaControl_ResponseWriteYMemArgList ;

#define DMMAmFmTunerDiranaControl_ResponseWriteYMemArgList_Init( p ) memset( p, 0, sizeof(*p) )
#define DMMAmFmTunerDiranaControl_ResponseWriteYMemArgList_Free( p ) // don't do anything


/**
 * Streaming Functions
 */
int DSIReadDMMAmFmTunerDiranaControl_ResponseWriteYMemArgList( DSIStream *stream, DMMAmFmTunerDiranaControl_ResponseWriteYMemArgList* arglist );
int DSIWriteDMMAmFmTunerDiranaControl_ResponseWriteYMemArgList( DSIStream *stream, const DMMAmFmTunerDiranaControl_ResponseWriteYMemArgList* arglist );




/**
 * Streaming Functions for Attributes
 */

DSI_EXTERN_C_END

#endif // DMMAMFMTUNERDIRANACONTROL_H
