/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by Voice CodeGen Version: R1_v1.3.0
* generated on: Tue Jun 21 15:32:43 IST 2016
*/
/**
 * author: EGMG_Tuner
 */
#ifndef V2_IVIRADIO_STATION_STATION_HPP_
#define V2_IVIRADIO_STATION_STATION_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Types.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v2 {
namespace IVIRadio {
namespace Station {

class Station {
public:
    virtual ~Station() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* Station::getInterface() {
    return ("IVIRadio.Station.Station");
}

CommonAPI::Version Station::getInterfaceVersion() {
    return CommonAPI::Version(2, 1);
}


} // namespace Station
} // namespace IVIRadio
} // namespace v2

namespace CommonAPI {
}


// Compatibility
namespace v2_1 = v2;

#endif // V2_IVIRADIO_STATION_STATION_HPP_
